language: erlang
otp_release:
  - 17.0
before_install:
  - git clone https://github.com/elixir-lang/elixir
  - cd elixir
  - git checkout v1.0.4
  - cd ..
  - make -C elixir
  - git clone https://github.com/jeremyjh/dialyxir
  - cd dialyxir
  - mix archive.build
  - echo y | mix archive.install dialyxir-0.2.6.ez
  - mix dialyzer.plt
  - cd ..
before_script:
  - export PATH="`pwd`/elixir/bin:$PATH"
  - mix local.hex --force
  - mix deps.get --only test
  - mix compile
  - mix dialyzer
script: mix test
after_script:
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
